name: Manual Docker Build & Scan

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Checkov scan
        uses: bridgecrewio/checkov-action@v12.2545.0
        with:
          directory: .
          quiet: true

      # Optional: Uncomment to use Snyk instead of Checkov
      # - name: Run Snyk scan
      #   uses: snyk/actions/docker@master
      #   env:
      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      #   with:
      #     image: myapp:latest
      #     dockerfile: Dockerfile

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest
